version: '3.8'

services:
  web:
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile
    volumes:
      - ../../:/app
      # Excluir venv local del contenedor para usar el del sistema (dentro del docker)
      - /app/.venv
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=dev_secret_key
      - API_BASE_URL=http://localhost:8000/api/v1
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASS=${ADMIN_PASS:-admin123456}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      # Si usas Geoapify, descomenta y a√±ade tu clave
      # - GEOAPIFY_API_KEY=tu_clave_aqui
    command: bash deployment/docker/entrypoint.sh
